---
- name: Install DCGM Exporter
  # hosts: gpu_cluster_a, gpu_cluster_b
  hosts: gpu_cluster_a
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - git
          - make
          - unzip
          - tar
          - dnf-plugins-core
          - wget
        state: present
  roles:
    - role: gantsign.golang
      golang_version: 1.22.3
      golang_gopath: /opt/go
    - role: dcgm_exporter
