---    
# - name: Create Munge Key
#   ansible.builtin.command: /usr/sbin/mungekey
#   args:
#     creates: /etc/munge/munge.key
#   when: "'master-node' in inventory_hostname"

- name: Create Munge Key
  command: /usr/sbin/create-munge-key -r -f
  when: "'master-node' in inventory_hostname"

- name: Change Key Owner
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
  when: "'master-node' in inventory_hostname"

- name: Put Munge Key in /tmp
  ansible.builtin.copy:
    src: "/etc/munge/munge.key"
    dest: "/tmp/munge.key"
    remote_src: yes
  when: "'master-node' in inventory_hostname"

- name: Copy Munge Key to local repor
  ansible.builtin.copy:
    src: "/tmp/munge.key"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: '0400'
    # remote_src: false
  when: "'master-node' not in inventory_hostname"

- name: Ensure a specific file is absent
  ansible.builtin.file:
    path: /tmp/munge.key
    state: absent

- name: Ensure munge service is running
  systemd:
    name: munge
    state: started
    enabled: yes

- name: Ensure munge service is restarted
  systemd:
    name: munge
    state: restarted
    enabled: yes