---    
- name: Copy Slurm configuration files
  copy:
    src: "sakura_conf/slurm.conf"
    dest: "/etc/slurm/slurm.conf"
    owner: root
    group: root
    # mode: 644

- name: Copy Prolog files
  copy:
    src: "sakura_conf/prolog.sh"
    dest: "/etc/slurm/prolog.sh"
    owner: slurm
    group: slurm
    mode: 755

- name: Copy Epilog files
  copy:
    src: "sakura_conf/epilog.sh"
    dest: "/etc/slurm/epilog.sh"
    owner: slurm
    group: slurm
    mode: 755

- name: Copy Gres files
  copy:
    src: "sakura_conf/gres.conf"
    dest: "/etc/slurm/gres.conf"
    owner: slurm
    group: slurm
    mode: 644
  when: "'a0' in inventory_hostname"

- name: Copy cgroup configuration files
  copy:
    src: "sakura_conf/cgroup.conf"
    dest: "/etc/slurm/cgroup.conf"

- name: Ensure /var/log/slurm is slurm-rw-able 
  ansible.builtin.file:
    path: "/var/log/slurm"
    state: directory
    owner: slurm
    group: slurm

- name: copy nhc config
  copy:
    src: "sakura_conf/nhc.conf"
    dest: "/etc/nhc/nhc.conf"
    owner: root
    group: root
    mode: 644
