---
- name: Test connectivity between all hosts
  hosts: all
  gather_facts: false
  vars:
    if_suffix:
      - "-2"
      - "-3"
      - "-4"
      - ""
  tasks:
    - name: Ping each host from every other host
      ansible.builtin.command:
        cmd: "ping -c 3 {{ item[0] }}{{ item[1] }}"
      loop: "{{ groups['all'] | product(if_suffix) | list }}"
