global:
  scrape_interval: 60s # change from 60s to 15s
  scrape_timeout: 10s
  external_labels:
    monitor: "gpu-alert-manager"

rule_files:
  - /etc/prometheus/alert.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node_exporter
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/node-exporter.node.yml
  - job_name: dcgm_exporter
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/dcgm-exporter.node.yml
