---
- name: Install and Run DCGM Exporter
  import_playbook: playbooks/install_dcgm_exporter.yml
- name: Install and Run Node Exporter
  import_playbook: playbooks/install_node_exporter.yml
- name: Install and Run Infiniband Exporter
  import_playbook: playbooks/install_infiniband_exporter.yml
- name: Install and Run PCM IIO Exporter
  import_playbook: playbooks/install_pcm_iio_exporter.yml
- name: Install and Run PCM PCIe Exporter
  import_playbook: playbooks/install_pcm_pcie_exporter.yml
- name: Install and Run PCM Memory Exporter
  import_playbook: playbooks/install_pcm_memory_exporter.yml
